# Generated by Django 5.0.6 on 2024-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('introduction', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('minutes', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
